# Numpy Practice Notebook

In [4]:
## first import numpy using an alias
import numpy as np

## Datatypes and attribute

In [2]:
# its main datatype is ndarray (n dimensional array)

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2,3.5],
             [4,5,6.5]])
a3 = np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])

In [8]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [9]:
type(a2)

numpy.ndarray

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
## in numpy axis 0 = rows
## axis 1 = columns
## axis 2 = n dimensions of the array
## this a3 array has a shape of 2,3,3 


In [12]:
## lets look at np attributes

In [13]:
a1.shape

(3,)

In [14]:
a2.shape

(2, 3)

In [15]:
a3.shape

(2, 3, 3)

In [16]:
## check dimensions
a1.ndim

1

In [17]:
a2.ndim

2

In [18]:
a3.ndim

3

In [19]:
## to check for types
a1.dtype

dtype('int32')

In [20]:
a2.dtype

dtype('float64')

In [21]:
a3.dtype

dtype('int32')

In [22]:
# you can also check for sizes
a1.size

3

In [23]:
a2.size

6

In [24]:
a3.size

18

In [26]:
## great work faith

In [27]:
## now lets create a Pandas Data frame from numpy
import pandas as pd

In [29]:
df = pd.DataFrame(a2)

In [30]:
df

0    1    2
0  1.0  2.0  3.5
1  4.0  5.0  6.5

In [31]:
## Great 

In [32]:
type(df)

pandas.core.frame.DataFrame

In [33]:
#hmmm...


## Creating Arrays in numpy

In [34]:
## its cool that we can create arrays ourselves in numpy but its also tiring
# let me create an array using numpy functions

In [40]:
ones =  np.ones((2,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
## defalult dtype 0s float64
ones.dtype

dtype('float64')

In [45]:
zeroes = np.zeros((6,5))
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
#3 lets look at numpy's random methods
random1 = np.random.randint(0,5, size=(3,5))

In [47]:
random1

array([[2, 1, 2, 2, 4],
       [3, 1, 1, 2, 2],
       [0, 1, 0, 2, 1]])

In [69]:
np.random.seed(2)
random2 = np.random.random((3,6))
random2

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ,
        0.33033482],
       [0.20464863, 0.61927097, 0.29965467, 0.26682728, 0.62113383,
        0.52914209],
       [0.13457995, 0.51357812, 0.18443987, 0.78533515, 0.85397529,
        0.49423684]])

In [70]:
np.random.seed(2)
random6 = np.random.random((3,6))
random6

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ,
        0.33033482],
       [0.20464863, 0.61927097, 0.29965467, 0.26682728, 0.62113383,
        0.52914209],
       [0.13457995, 0.51357812, 0.18443987, 0.78533515, 0.85397529,
        0.49423684]])

In [71]:
## nice work faith
# the random seed helps to keep the numbers stable without changing incase of sharing your notebook
## that means the random generated  numbers are not actually random, they are pseudo random numbers


In [59]:
random3 = np.random.rand(3,4,2)

In [65]:
random3

array([[[0.24428982, 0.38406474],
        [0.66066762, 0.39887224],
        [0.99417857, 0.67694733],
        [0.92754815, 0.43274131]],

       [[0.95776004, 0.17669287],
        [0.75904895, 0.22570017],
        [0.74919137, 0.78324043],
        [0.09386711, 0.32471562]],

       [[0.48567859, 0.96740507],
        [0.34587189, 0.12886182],
        [0.14754746, 0.06377291],
        [0.41187389, 0.57848214]]])

In [54]:
## great work faith

In [2]:
numrange = np.arange(10,100,4)

NameError: name 'np' is not defined

In [3]:
numrange

NameError: name 'numrange' is not defined

## Viewing Arrays and Matrices

In [5]:
a1

NameError: name 'a1' is not defined

In [73]:
a1.ndim

1

In [74]:
a1[1]

2

In [75]:
a3


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [78]:
a3[0,1]

array([4, 5, 6])

In [83]:
a3[:2,1:3,:1]

array([[[ 4],
        [ 7]],

       [[13],
        [16]]])

In [8]:
np.unique(a3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [9]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a3[0,0]

array([1, 2, 3])

In [11]:
a3[0,0,0]

1

In [12]:
a3[:1,:2,:1]

array([[[1],
        [4]]])

In [13]:
a3[:2,:1,:1]

array([[[ 1]],

       [[10]]])

In [14]:
a4 = np.random.randint(10, size=(2,4,6,7))

In [15]:
a4

array([[[[8, 0, 4, 7, 9, 2, 2],
         [6, 3, 7, 2, 6, 2, 1],
         [2, 0, 4, 8, 2, 2, 1],
         [9, 1, 7, 9, 5, 6, 3],
         [4, 9, 2, 9, 8, 8, 2],
         [6, 0, 2, 5, 6, 6, 1]],

        [[1, 5, 7, 7, 1, 9, 7],
         [6, 2, 9, 1, 9, 3, 9],
         [9, 1, 5, 9, 1, 8, 4],
         [3, 5, 0, 5, 4, 2, 0],
         [4, 5, 2, 2, 1, 5, 2],
         [2, 7, 9, 6, 6, 3, 9]],

        [[1, 8, 6, 8, 0, 1, 9],
         [5, 9, 8, 6, 8, 5, 5],
         [5, 5, 9, 6, 1, 7, 6],
         [8, 8, 8, 6, 2, 0, 2],
         [6, 7, 9, 4, 5, 9, 6],
         [0, 8, 9, 2, 8, 3, 6]],

        [[7, 5, 3, 0, 6, 6, 0],
         [6, 3, 6, 8, 2, 4, 6],
         [0, 8, 2, 0, 0, 9, 7],
         [4, 2, 7, 7, 0, 0, 7],
         [8, 1, 0, 2, 6, 0, 0],
         [8, 2, 4, 8, 2, 5, 5]]],


       [[[7, 8, 4, 8, 0, 3, 5],
         [3, 2, 4, 4, 1, 0, 0],
         [2, 2, 3, 6, 1, 9, 6],
         [9, 4, 0, 2, 2, 1, 6],
         [6, 2, 7, 2, 5, 8, 7],
         [3, 7, 9, 1, 8, 4, 6]],

        [[1, 9, 6, 8, 9, 0, 

In [16]:
# cool now let me play with this
# list all the first columns of each matrix

In [17]:
a4[:2,:4,:7,:1]

array([[[[8],
         [6],
         [2],
         [9],
         [4],
         [6]],

        [[1],
         [6],
         [9],
         [3],
         [4],
         [2]],

        [[1],
         [5],
         [5],
         [8],
         [6],
         [0]],

        [[7],
         [6],
         [0],
         [4],
         [8],
         [8]]],


       [[[7],
         [3],
         [2],
         [9],
         [6],
         [3]],

        [[1],
         [3],
         [9],
         [3],
         [6],
         [8]],

        [[7],
         [2],
         [1],
         [2],
         [8],
         [5]],

        [[0],
         [4],
         [3],
         [2],
         [0],
         [0]]]])

In [19]:
## great work 
## now show the last two numbers of every last column

In [30]:
a4[:2,:4,4:6,6:8]

array([[[[2],
         [1]],

        [[2],
         [9]],

        [[6],
         [6]],

        [[0],
         [5]]],


       [[[7],
         [6]],

        [[6],
         [6]],

        [[8],
         [5]],

        [[1],
         [8]]]])

In [31]:
## great work faith